version: '3.8'

services:
  app:
    build: .
    container_name: headlines_news_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CREATOR_ID=${CREATOR_ID}
    volumes:
      - .:/app
    restart: always
